### ISSUE TITLE
Reduce size of tweet table

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-backend#16]
Per @shaochengcheng we can eliminate tweets without URLs in the existing database, and prevent storing them in the future.

**Comment by filmenczer** [comment]
Assigned @shaochengcheng again as he explained that this is a more complex job than we thought at first. We also need to delete tweet rows in which there is a URL but it is not to one of our sources. To do this we must join with the URL table, because the tweet table only has shortened URLs. However, as the old parser failed in some cases, there may be URLs that we want and that are not in the URL table. Therefore, first we need to check with the new parser if missing URLs need to be added. Then we can do the join and clear up the tweet table.

**Comment by ZacMonroe** [comment]
We should also check that if the tweet DOES contain a URL but it is not in a target domain, then that URL should not be parsed nor stored.

**Comment by filmenczer** [comment]
All that remains to be done is to clean up old tweets in DB without a URL

**Comment by filmenczer** [comment]
@shaochengcheng it seems we could proceed with this, now that the new tweet parser is in place. Can @chathuriw be of assistance?

**Comment by shaochengcheng** [comment]
In total, 10,747,535 tweets are deleted, two tables are affected that are `tweet` and `ass_tweet`. 

No vacuum operation was taken, if we do need, please run it. Now I close this issue.
