### ISSUE TITLE
Lucene query string parser option `use_lucene_syntax`

### ISSUE THREAD

**Issue by shaochengcheng** [IUNetSci/hoaxy-backend#19]
How we provide the default behavior when parsing the query string by Lucene, specifically, the `use_lucene_syntax` option in the API.

I am thinking to provide three values for this field:

- False, do not use Lucene syntax
- True, do use Lucene syntax
- None, inferring it by the query string that tries to parse it as Lucene syntax if an error occurs then do parse without Lucene syntax.

And the default could be set to None.

**Comment by glciampaglia** [comment]
The documentation for Lucene syntax is here: https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

**Comment by filmenczer** [comment]
We decided to put this aside for the time being, given finite resources.
