### ISSUE TITLE
default crontab contains errors

### ISSUE THREAD

**Issue by fhamborg** [IUNetSci/hoaxy-backend#2]
The crontab that hoaxy produces if creating a fresh config directory is erroneous. The excerpt below contains a command `hoaxy site --crawl ...`, which however, should actually be `hoaxy crawl --fetch-url ...`
```
# hoaxy: fetch article update every hour
0 * * * * source activate hoaxy && hoaxy site --crawl --fetch-url --update > /dev/null
```

**Comment by shaochengcheng** [comment]
Yes. Some commands in crontab.sample.txt were changed. Please use https://github.com/IUNetSci/hoaxy-backend/blob/master/hoaxy/data/samples/crontab.sample.txt, Or update your version of hoaxy.

Thanks for your report.
Chengcheng
