### ISSUE TITLE
TopArticle API failing intermittently

### ISSUE THREAD

**Issue by yangkcatiu** [IUNetSci/hoaxy-backend#24]
![screen shot 2018-11-29 at 12 24 17 pm](https://user-images.githubusercontent.com/31357713/49239838-b8dce980-f3d1-11e8-8fe6-4cab2b443afc.png)

**Comment by filmenczer** [comment]
This is the error we discussed with @glciampaglia at our last meeting. Ben will take care of the exception in the front end so the website is usable again, but @shaochengcheng should look into this problem on the back-end.

**Comment by filmenczer** [comment]
Discussed; cannot find traces of the error in logs; will keep issue open.

**Comment by ZacMonroe** [comment]
We have not observed problems for a couple months; closing for now.
