### ISSUE TITLE
Control panel

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-backend#27]
For non-technical users, such as newsrooms, we would like a more friendly way (compared to CLI) to modify the config file. Idea: a control panel to manage backend settings like domain lists and API keys, on the fly.

**Comment by ZacMonroe** [comment]
We discussed this, and we decided to work toward a simple web interface for quick-install and for changing configuration options.
This should work after we have a friendly way to install Hoaxy with Docker.
- [ ] Domains to track
- [ ] API Keys
- [ ] Restart Hoaxy after changing configuration options

**Comment by lucmski** [comment]
Hi,

Hope you are all well !

Just to share with you a dockerfile on my fork: https://github.com/lucmski/hoaxy-backend
https://github.com/lucmski/hoaxy-backend/blob/dockerize/Dockerfile
https://github.com/lucmski/hoaxy-backend/blob/dockerize/docker-compose.yml

For a backend, I would suggest (py3):
https://github.com/aio-libs/aiohttp_admin/tree/master/demos/blog_react

For fetching tweets (py3):
https://github.com/twintproject/twint/wiki/Commands

For managing queues of twitter topics (nsq):
https://github.com/jaumecapdevila/seen-in-twitter

Cheers

**Comment by chathuriw** [comment]
Hi @lucmski, 

Thank you for your contribution. I tried to build the image from the docker file and got the following error. 

Get:9 http://deb.debian.org/debian stretch-updates/main amd64 Packages 2019-01-26-1412.04.pdiff [3276 B]
Get:10 http://deb.debian.org/debian stretch-updates/main amd64 Packages 2019-02-21-2009.35.pdiff [4149 B]
Get:10 http://deb.debian.org/debian stretch-updates/main amd64 Packages 2019-02-21-2009.35.pdiff [4149 B]
Get:11 http://deb.debian.org/debian stretch/main amd64 Packages [7084 kB]
Fetched 8020 kB in 1s (5839 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '20161107~bpo8+1' for 'ca-certificates-java' was not found
The command '/bin/sh -c apt-get update     && apt-get install -y ca-certificates-java='20161107~bpo8+1' openjdk-8-jdk     && apt-get install -y ant build-essential nano jq libssl1.0.0 libssl-dev' returned a non-zero code: 100

Any idea what causing this ?

**Comment by lucmski** [comment]
> Hi @lucmski,
> 
> Thank you for your contribution. I tried to build the image from the docker file and got the following error.
> 
> Get:9 http://deb.debian.org/debian stretch-updates/main amd64 Packages 2019-01-26-1412.04.pdiff [3276 B]
> Get:10 http://deb.debian.org/debian stretch-updates/main amd64 Packages 2019-02-21-2009.35.pdiff [4149 B]
> Get:10 http://deb.debian.org/debian stretch-updates/main amd64 Packages 2019-02-21-2009.35.pdiff [4149 B]
> Get:11 http://deb.debian.org/debian stretch/main amd64 Packages [7084 kB]
> Fetched 8020 kB in 1s (5839 kB/s)
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Version '20161107bpo8+1' for 'ca-certificates-java' was not found
> The command '/bin/sh -c apt-get update && apt-get install -y ca-certificates-java='20161107bpo8+1' openjdk-8-jdk && apt-get install -y ant build-essential nano jq libssl1.0.0 libssl-dev' returned a non-zero code: 100
> 
> Any idea what causing this ?

can u try with this one using alpine ?
https://gist.github.com/lucmski/87f13b669422c2f057b500404a01d359

**Comment by filmenczer** [comment]
After discussion, we decided that the main functionality of this improvement is captured by BotSlayer to **some** extent: it can be used to track links to selected articles specified in the query. although not all links from a domain. Also, giving front-end access to server configuration is ilikely to open security issues. Therefore we are moving this issue to utopia.
