### ISSUE TITLE
Move Hoaxy logs

### ISSUE THREAD

**Issue by ZacMonroe** [IUNetSci/hoaxy-backend#31]
Update the config file so that the logs are stored on /l/cnets (GFS) rather than the truthy user home directory, and move the logs that are currently there.

**Comment by chathuriw** [comment]
It seems we can't change the config of hoaxy.log, in order to change the path, we need to change hoaxy-home.

**Comment by filmenczer** [comment]
@shaochengcheng explains that the log is configured on a rotation, so it should not take too much space --- only around 350MB.
