### ISSUE TITLE
Check dashboard botscores

### ISSUE THREAD

**Issue by ZacMonroe** [IUNetSci/hoaxy-backend#32]
The cron job that gets the Botometer scores to put into the dashboard can fail (returning n/a) possibly because of RapidAPI or Botometer API rate issues. Slow down the requests and/or add a check that retries after a while.

**Comment by filmenczer** [comment]
Currently failing... No scores showing on the dashboard. 

What keys are we using? Let's also make sure we're using a correct set of keys...

**Comment by filmenczer** [comment]
We updated the keys to use the official @Truthyatindiana Hoaxy app and it works again!
