### ISSUE TITLE
Article parser title and date

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-backend#34]
We need to check why paper3k and mercury are failing in retrieving titles (and dates) when parsing articles such as https://www.snopes.com/fact-check/ocasio-cortez-price-is-right/

Then we will need to re-parse the articles that currently have null title (and date?) in the DB.

**Comment by chathuriw** [comment]
If the title is not returning from newspaper3k, parser will try mercury parser. After that, I updated the status_code in URL table to 40 for articles that have empty titles and reparse the articles.
