### ISSUE TITLE
Test and revise article parsing pipeline

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-backend#36]
Test (and also analyze hoaxy backend log) to measure how often one or the other parser fails/succeeds at getting all required fields. Note that if content is indeed empty, that should not be interpreted as a parser error. We may need to revise the pipeline based on these results, eg, switch order, use both and merge fields, or add other parser...

**Comment by ZacMonroe** [comment]
For most fields, a merged strategy of parsing works.
- For the title field, if it cannot be found, then we skip the article.
- For the date_published field, if it cannot be found, then we set it to the empty string.
- For the dek field, it's never found so we set it to empty.
- For the author field, if it cannot be found, we set it to the empty string.

@shaochengcheng, would you please check that all of the above is okay and will not cause problems downstream? In particular, if we set date_published to the empty string, will that cause problems (namely when ranking by recent)?

**Comment by ZacMonroe** [comment]
The plan for merging the two parsers' results is to first use Mercury, and if any fields are missing, try to fill them with newspaper3k.

**Comment by shaochengcheng** [comment]
@ZacMonroe, the working flow sounds good for me. `date_published` could be empty for a parsed article in the database. However, when doing index or outputting API service, we should merge it with `date_captured` column. Our current code has already taken care of it, e.g., [lucene index](https://github.com/IUNetSci/hoaxy-backend/blob/master/hoaxy/commands/lucene_cmd.py), mostly by utilizing the SQL function `coalesce(a.date_published, a.date_captured) AS pd`, thus you are ok to do it.

**Comment by filmenczer** [comment]
If I understand @shaochengcheng 's feedback (thank you!), we need to check that `date_published` and `date captured` are merged when the API returns recent results (sorted by date). Then we can proceed.

**Comment by chathuriw** [comment]
I change the code to use mercury parser first and set the default to NULL.
