### ISSUE TITLE
docker-compose / cache / queues

### ISSUE THREAD

**Issue by lucmski** [IUNetSci/hoaxy-backend#39]
Hi,

Hope you are all well !

Just was wondering if hoaxy would be soon released as a docker-compose for the front and back end as a quick starter. 

Have u added httpcache (x-vary) middleware (eg https://github.com/gregjones/httpcache) or twitter accounts queueing to the task list (eg. https://github.com/Nedja995/twint_server) ?

Thanks for the hard work ^^

Cheers

**Comment by filmenczer** [comment]
Working on Docker (#26). In the meanwhile, an AMI is available for EC2 (see https://github.com/IUNetSci/hoaxy-backend#hoaxy-backend-as-aws-image-ami).

Not sure about other questions...

**Comment by lucmski** [comment]
I meant is it possible to distribute a list of twitter usernames to fetch and get their botometer score async like with payloads managed by rabbitmq or celery. Globally, it is more about handling more data and being able to resume tasks. (get the last tweet id scraped so it prevents using resources).

**Comment by lucmski** [comment]
Example for a front/server dockerfile (alpine/nodejs v11.x):
https://gist.github.com/lucmski/b4a143b0bf026448f159e6bf463ed0c2

Example for hoaxy-backend (alpine 3.9/mininconda2):
https://gist.github.com/lucmski/87f13b669422c2f057b500404a01d359

If needed, I can do a miniconda3...

**Comment by chathuriw** [comment]
Thank you for your contribution @lucmski. I will check the docker files and let you know.

**Comment by chathuriw** [comment]
@lucmski, I'm trying the docker file for hoaxy-backend. I was able to follow first three steps. I'm stucked with step 4 (https://gist.github.com/lucmski/87f13b669422c2f057b500404a01d359#run-docker-container). 
I think there is a typo in the first command in that step. (docker -ti --rm lucmichalskip/hoaxy-backend:alpine-miniconda2-jdk8 hoaxy -h)

I'm getting this error. "unknown shorthand flag: 't' in -ti"

**Comment by lucmski** [comment]
forgot to add 'run' command sorry, the gist was updated

**Comment by chathuriw** [comment]
@lucmski Can you share the Dockerfile lucmichalskip/hoaxy-backend:alpine-miniconda2-jdk8 with us. I'm trying to follow your instructions again and got an error in docker run command. I think it will be easier to troubleshoot if I can see the Dockerfile.

chathuri@chathuri-Latitude-E7450:~/IUNI/hoaxy-backend$ docker run -ti --rm lucmichalskip/hoaxy-backend:alpine-miniconda2-jdk8 hoaxy -h
/opt/conda/lib/python2.7/site-packages/hoaxy-0.1.0-py2.7.egg/hoaxy/__init__.py:30: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "/opt/conda/bin/hoaxy", line 11, in <module>
    load_entry_point('hoaxy==0.1.0', 'console_scripts', 'hoaxy')()
  File "build/bdist.linux-x86_64/egg/hoaxy/commands/cmdline.py", line 80, in main
  File "build/bdist.linux-x86_64/egg/hoaxy/utils/__init__.py", line 20, in list_cls_under_mod
  File "/opt/conda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "build/bdist.linux-x86_64/egg/hoaxy/commands/crawl.py", line 12, in <module>
  File "build/bdist.linux-x86_64/egg/hoaxy/crawl/spiders/article.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/hoaxy/database/__init__.py", line 27, in <module>
  File "/opt/conda/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 423, in create_engine
    return strategy.create(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/opt/conda/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 605, in dbapi
    import psycopg2
  File "/opt/conda/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by lucmski** [comment]
Hi,

Sounds that even my dockerfile is outdated; i need to update it.
Why do not you split into separate service with a docker-compose ?

My telegram is @deepocrates for faster communication.

Cheers,
L

**Comment by roscopecoltran** [comment]
From fork, https://github.com/lucmski/hoaxy-backend/tree/dockerize-p3/docker

please try:
```
git clone https://github.com/lucmski/hoaxy-backend
cd hoaxy-backend/docker
docker build -t hoaxy .
docker run -ti --rm hoaxy -h
```

**Comment by chathuriw** [comment]
@lucmski merged the docker changes to master. Thank you for your contribution.
