### ISSUE TITLE
Handling the 502 proxy error from Botometer API

### ISSUE THREAD

**Issue by yangkcatiu** [IUNetSci/hoaxy-backend#41]
We can add a extra `requests.exceptions.HTTPError` to the following line:

https://github.com/IUNetSci/hoaxy-backend/blob/f0eb49e8d316f5a8a29b1f30023e5d803f45cff3/hoaxy/commands/report.py#L100

So that when the proxy error happens, Hoaxy will try again for 3 times.

**Comment by chathuriw** [comment]
Added HTTPError in https://github.com/IUNetSci/hoaxy-backend/commit/e2867ac8e388448ebb5a682de0f15b5126988f2d
