### ISSUE TITLE
Replace old mashape base URL with rapidAPI

### ISSUE THREAD

**Issue by yangkcatiu** [IUNetSci/hoaxy-backend#42]
https://p.mashape.com => https://p.rapidapi.com

**Comment by filmenczer** [comment]
Also update the HTTP headers using 'Mashape' or 'MASHAPE'. For new headers see https://docs.rapidapi.com/docs/headers-sent-by-mashape-proxy2

**Comment by chathuriw** [comment]
Added in commit https://github.com/IUNetSci/hoaxy-backend/commit/5380cea0163b762146b9fb30ef85020d459226b0 and deployed in the production.

**Comment by yangkcatiu** [comment]
It seems there are still some mashape.com based URLs in the backend, for example, the one that fetches botscores.

We probably need to do a search to find all of them.

**Comment by yangkcatiu** [comment]
We should probably also update the README file about mashape=>rapidAPI

**Comment by filmenczer** [comment]
This was due to the `botometer-python` library. @chathuriw updated to the latest version (1.4), which should fix the issue. Can close as soon as README is updated.

**Comment by chathuriw** [comment]
Updated the README, config and code references (https://github.com/IUNetSci/hoaxy-backend/commit/831b8d2def079a8a6a8224a5ec1958e3c791ac6c)
