### ISSUE TITLE
Tweet URL

### ISSUE THREAD

**Issue by ChrisTorresLugo** [IUNetSci/hoaxy-backend#43]
The Tweet URLs stored in the file that Hoaxy generates seem link to a version of a tweet that only has the first 140 characters, instead of the new max of 280 characters. For example:

This is the link saved by Hoaxy: https://twitter.com/DonGoyoOficial/status/1151497327330365441

This is the result of that link (notice the RT at the beginning and the 3 dots at the end):

<img width="444" alt="Screen Shot 2019-08-11 at 5 13 31 PM" src="https://user-images.githubusercontent.com/7763583/62839757-16ae1a80-bc5d-11e9-8aec-3ad35b2cd1ed.png">

Here is the same tweet on that user's account:

<img width="441" alt="Screen Shot 2019-08-11 at 5 13 42 PM" src="https://user-images.githubusercontent.com/7763583/62839758-1ca3fb80-bc5d-11e9-94be-66890b481916.png">

Here is the same tweet when using search:

<img width="449" alt="Screen Shot 2019-08-11 at 5 25 43 PM" src="https://user-images.githubusercontent.com/7763583/62839760-20378280-bc5d-11e9-9e26-6f34f2e8bcc0.png">

This seems to be a compatibility mode link. If it is, then there has to be an extended mode link.  

Should this link be updated to point to a tweet's full text (if possible)?

**Comment by filmenczer** [comment]
We discussed it. This is how Twitter shows retweeted tweets. The URL is correct.
