### ISSUE TITLE
Docker build fail on jcc install

### ISSUE THREAD

**Issue by bwindeler** [IUNetSci/hoaxy-backend#52]
```docker-compose up``` failed on line 96 of Dockerfile

```
    && JCC_JDK=/usr/lib/jvm/default-jvm python setup.py install \
```
[permalink](https://github.com/IUNetSci/hoaxy-backend/blob/61b1cfd80da9efbc932ae8d965560501553dbb2e/docker/Dockerfile#L92-L99)

Error message:
```/opt/conda/compiler_compat/ld: cannot find -lpython3.8m```

Seems to be a python 3.8 compatibility issue

I added ```python=3.7.5``` to the conda install at line 47 to fix and the image built successfully

**Comment by bwindeler** [comment]
Some additional fixes:

add mercury parser CLI install to Dockerfile (after changing to workdir /opt/):

```RUN apk add --update nodejs npm
RUN npm install -g mercury-parser```

call CLI instead of node script in ar

**Comment by chathuriw** [comment]
@bwindeler thank you for the contribution. I added what you suggested.
