### ISSUE TITLE
Add AltNews.in And BoomLive.in as fact checkers

### ISSUE THREAD

**Issue by rootkea** [IUNetSci/hoaxy-backend#53]
Hello!

I India has the largest number of social media users and so consequently the problem of fake news has been the worst in India.
[India Has a Public Health Crisis. It’s Called Fake News.](https://www.nytimes.com/2019/04/29/opinion/india-elections-disinformation.html)

When I tried searching Hoaxy on https://hoaxy.iuni.iu.edu/ I couldn't find India specific content even when I used India specific search terms in "Articles". Seems that the India-specific fact-checkers haven't been added to Hoaxy.

I would like to request you to please add 1. [AltNews.in](https://en.wikipedia.org/wiki/AltNews.in) and 2. BoomLive.in - both are certified by International Fact Checking Network.[0][1]

Thank you!

[0] https://ifcncodeofprinciples.poynter.org/application/public/pravda-media-foundation/D27BB43D-D8FC-F85B-1C25-2AF73DF3A12C
[1] https://ifcncodeofprinciples.poynter.org/application/public/boom/BEE99226-33F7-4B33-9B78-F0F98F51E991

**Comment by filmenczer** [comment]
The version of Hoaxy at hoaxy.iuni.iu.edu is based on US low-credibility and fact-checking sources. We are unable to add sources from other countries.

However, Hoaxy is open source and you are welcome to create a version for India with all the sources you wish to include.
