### ISSUE TITLE
Make it easier and document how to update source list

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/hoaxy-backend#55]
Ideally, updating the list of sources (domains) should be as easy as updating the file and/or the configuration file and restarting the system. But recently we learned that it's much more complicated, and there is no documentation about how to do it. 

If possible, we should make it as easy as described above. Else there should be a command to update the list. And this has to be documented.

In the future we expect the list to change often, possibly automatically, therefore the update system should be compatible with that.

@shaochengcheng is this possible?

**Comment by shaochengcheng** [comment]
Yes, I will make it as easier as one-line command.




------------------&nbsp;Original&nbsp;------------------

**Comment by mohawk2** [comment]
This issue shows up as an "easy start to contributing to this project". @shaochengcheng If you have an idea how to achieve it but it's not yet a priority for you, what do you think of at least outlining here the approach you'd take to make it easier for someone else to run with?

**Comment by filmenczer** [comment]
@mohawk2 thanks for the offer. This turned out to be more complicated than anticipated and we're working on it. If you are still interested, perhaps consider this other issue: #58 or some of the front-end issues: https://github.com/IUNetSci/hoaxy-frontend/issues?q=is%3Aopen+is%3Aissue+milestone%3AImprovements

**Comment by chathuriw** [comment]
To add new list of sites, we can use this command : 

hoaxy site --load-domain --exclusive --site-type=claim  --ignore-redirected --ignore-inactive /home/data/apps/hoaxy/hoaxy-backend-config/domains_claim_fify.txt

If 'exclusive' specified, it will disable the existing claim sites in the database.
