### ISSUE TITLE
A bug in network construction

### ISSUE THREAD

**Issue by yangkcatiu** [IUNetSci/hoaxy-backend#61]
Line https://github.com/IUNetSci/hoaxy-backend/blob/0f1386e787de2f4ed0d12c6e28c5520dd3d1eed9/hoaxy/ir/search.py#L757 tries to extract the `in_reply_screen_name` field in the tweet object, however, the correct spelling is `in_reply_to_screen_name`.

A possible consequence of the bug is that the final graph doesn't contain the reply edges.

**Comment by benabus** [comment]
Typo should be corrected or removed.

**Comment by chathuriw** [comment]
Removed the function at https://github.com/IUNetSci/hoaxy-backend/commit/bf70d18cd290f5181703f912535d8cf5c6ef2720
