### ISSUE TITLE
Hoaxy Community AMI

### ISSUE THREAD

**Issue by vinaysetty** [IUNetSci/hoaxy-backend#63]
Hi,

I checked in AWS there is no Hoaxy Community AMIs anymore! was it removed?

VS

**Comment by filmenczer** [comment]
Is this about Hoaxy or BotSlayer? If the latter, please check the Ohio region as explained in the directions. Please do not post issues about BotSlayer here.

**Comment by filmenczer** [comment]
Sorry please disregard the above comment.

**Comment by filmenczer** [comment]
You should set your AWS service region to US East (Ohio) before searching (Account attributes in the top right corner of the page -> Settings -> Zones).

**Comment by dehma01** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/49675319/200816118-ef0076bc-4741-4fbf-99ed-78fe1b4e29ec.png">

I have the same issue

**Comment by benabus** [comment]
Unfortunately, due to costs, we needed to remove the AMI over the summer.  The documentation here was never updated.  Apologies for the inconvenience.
