### ISSUE TITLE
Error when running hoaxy init

### ISSUE THREAD

**Issue by awallemo** [IUNetSci/hoaxy-backend#65]
File "/home/ubuntu/anaconda2/envs/hoaxy/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/ubuntu/anaconda2/envs/hoaxy/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"

I'm getting this error when I run the hoaxy init command. I've done all the steps before correctly. I have made a user, password, database and they are using port 5432 with localhost. I have specified all this info in the conf.yaml file yet I get this error every time.

**Comment by glciampaglia** [comment]
Hello,
What is the name of the database user you created? The error says that user "postgres" could not login, is that the user name you chose?

**Comment by awallemo** [comment]
Hi gicimpaglia, I managed to resolve the issue. The problem was I created the users in postgres locally on my mac and not on the virtual machine where I was doing everything else.
