### ISSUE TITLE
Dockerfile link update

### ISSUE THREAD

**Issue by RobertAndion** [IUNetSci/hoaxy-backend#68]
The current docker file fails to build when reaching the RUN step on lines 72 and 73. By changing the link and cp commands to these, it allows it to build however I am not sure if this version is compatible with hoaxy. I have been unable to thoroughly test this.
```
RUN curl https://downloads.apache.org/ant/ivy/2.5.0/apache-ivy-2.5.0-bin.tar.gz | tar -xz --strip-components=1 \
    && cp ivy-2.5.0.jar /root/.ant/lib/
```

**Comment by chathuriw** [comment]
@RobertAndion thank you for the contribution. It works with new ivy version.
