### ISSUE TITLE
Ignore false matches by default, change configuration on private instance

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-backend#8]
We need to make sure that the tweets that match the filter of the Twitter Streaming API but do not contain actual links should be dropped and not added to the database. There is an option for it in the configuration file. We should make dropping the default. 

@shaochengcheng should also update the configuration file of our own private instance at hoaxy.iuni.iu.edu

**Comment by shaochengcheng** [comment]
Private configuration is updated. The issue should be closed.
