### ISSUE TITLE
Site config from the production version

### ISSUE THREAD

**Issue by manoelhortaribeiro** [IUNetSci/hoaxy-backend#9]
First of all, thank you heaps for making this project open-source. I spent literally the whole morning crawling through the files and quality of code is very impressive.

I got really interested in the "site_tags" features, and would like to know if:

1) Is there any automated way to add these tags from the tables you guys mentioned? I've found the opensource lists, but it would be helpful if thats already done.

2) If not, is there any chance you guys provide me with the site config used in the version currently deployed at (https://hoaxy.iuni.iu.edu/)?

For the project I have in mind I'd probably have to add some scripts to automatically increase the list of sources to query from. I'd be very glad to contribute with what I add if you guys deem it as valuable for the tool.

Thanks again,
Manoel

**Comment by glciampaglia** [comment]
Thank you for the appreciate words Manoel, and my apologies for taking time to get back to this ticket, I saw it last week but I was on the road. I am not aware of any automated way to populate the site_tag table. Regarding our current configuration, this is what we have in the production instance of Hoaxy:

```
hoaxy=> select id,name,source from site_tag;
 id |    name     |      source       
----+-------------+-------------------
  1 | hoax        | fakenewswatch.com
  2 | satire      | fakenewswatch.com
  3 | clickbait   | fakenewswatch.com
  4 | bias        | opensources.co
  5 | conspiracy  | opensources.co
  6 | unreliable  | opensources.co
  7 | satire      | opensources.co
  8 | fake        | opensources.co
  9 | clickbait   | opensources.co
 10 | junksci     | opensources.co
 11 | political   | opensources.co
 12 | rumor       | opensources.co
 13 | junkscience | opensources.co
(13 rows)
```

We do appreciate any kind of feedback, and if you have any bugfix or feature, feel free to send us a pull request!

Cheers

Giovanni
